/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COM.APP.UTS045;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Tsabit Alifudin
 */
public class AplikasiDataMahasiswa extends javax.swing.JFrame {
    //membuat object dari mahasiswa
    private MahasiswaTableModel model;
    //membuat list untuk menampung data
    private List<pelanggan> listData;
    /**
     * Creates new form AplikasiDataMahasiswa
     */
    public AplikasiDataMahasiswa() {
        initComponents();
        //memposisikan table di tengah
        setLocationRelativeTo(null);
        //pengambilan data secara manual
        initData();
        //memasukkan data ke model
        model = new MahasiswaTableModel(listData);
        //memasukkan data dari model ke table mahasiswa
        tableMahasiswa.setModel(model);
    }

    //Membuat Fungsi Tambah Data
    public void addMahasiswa(pelanggan mahasiswa){
        //Memasukkan data baru ke list Mahasiswa
        listData.add(mahasiswa);
        //memasukkan data ke model
        model = new MahasiswaTableModel(listData);
        //memasukkan data dari model ke table mahasiswa
        tableMahasiswa.setModel(model);
    }
    
    //Membuat Fungsi Update Data
    public void updateMahasiswa(pelanggan mahasiswa){
        //Mencari NIM Mahasiswa
        pelanggan mhs = cari(mahasiswa.getIdPart());
        //Pengecekan tidak sama dengan null
        if (mhs != null ) {
            listData.remove(mhs);
            //Memasukkan data baru ke list Mahasiswa
            listData.add(mahasiswa);
            //memasukkan data ke model
            model = new MahasiswaTableModel(listData);
            //memasukkan data dari model ke table mahasiswa
            tableMahasiswa.setModel(model);
            //Pemberian Notice Ubah Data
            JOptionPane.showMessageDialog(this, "Ubah Data Berhasil!");
        }
    }
    
    //Membuat Fungsi Cari
    public pelanggan cari(String nim){
        for (pelanggan m : listData) {
            if (m.getIdPart().equals(nim)) {
                //kalau ditemukan
                return m;
            }
        }
        //Kalau tidak ditemukan
        return null;
    }
    
    //Membuat Fungsi Hapus Data
    private void deleteMahasiwa(String nim){
        //Mencari nim
         pelanggan mhs = cari(nim);
         //Menghapus data
         listData.remove(mhs);
         //memasukkan data ke model
         model = new MahasiswaTableModel(listData);
         //memasukkan data dari model ke table mahasiswa
         tableMahasiswa.setModel(model);
         //Pemberian Notice Hapus Data
         JOptionPane.showMessageDialog(this, "Hapus Data Berhasil!");
    }
    
    //pembuatan fungsi initData();
    private void initData(){
        //pemanggilan listData
        listData = new ArrayList<>();
        //pembuatan class mahasiswa dan pengisian data ke mahasiswa
        pelanggan mahasiswa = new pelanggan();
           // ("1", "Tsabit Alifudin", "as","dk", "12", "12");
        //memasukkan data ke listData mahasiswa
        listData.add(mahasiswa);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Data Mahasiswa");

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMahasiswa.setRowHeight(24);
        tableMahasiswa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMahasiswa.getTableHeader().setResizingAllowed(false);
        tableMahasiswa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableMahasiswa);

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonUbah)
                        .addComponent(buttonHapus)
                        .addComponent(buttonKeluar))
                    .addComponent(buttonTambah))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        //Pemanggilan Class MahasiswaDetail
        MahasiswaDetail detail = new MahasiswaDetail(this, true);
        //Menampilkan Panel MahasiswaDetail
        detail.setVisible(true); 
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        //Mengambil Nim yang akan diupdate
        int index = tableMahasiswa.getSelectedRow();
        //Pemilihan User diatas index 0
        if (index >= 0) {
            //User memilih index pertama dalam table, yaitu nim 
            String nim = tableMahasiswa.getValueAt(index, 0).toString();
            //Pemanggilan Class MahasiswaDetail
            MahasiswaDetail detail = new MahasiswaDetail(this, true, nim);
            //Menampilkan Panel MahasiswaDetail
            detail.setVisible(true); 
        }
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        //Mengambil Nim yang akan diupdate
        int index = tableMahasiswa.getSelectedRow();
        //Pemilihan User diatas index 0
        if (index >= 0) {
            //Pemberian Notice Yakin Menghapus
            boolean yakin = JOptionPane.showConfirmDialog(this, "Apakah anda Yakin ?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
            //kalau yakin
            if (yakin) {
                 //User memilih index pertama dalam table, yaitu nim 
                String nim = tableMahasiswa.getValueAt(index, 0).toString();
                deleteMahasiwa(nim);
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        //Pembuatan Notice Keluar
        boolean yakin = JOptionPane.showConfirmDialog(this, "Yakin akan Keluar?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
        //iya keluar
        if (yakin) {
            System.exit(0);
        }
    }//GEN-LAST:event_buttonKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiDataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMahasiswa;
    // End of variables declaration//GEN-END:variables
}
